var $homepage_test = $('[av-group="homepage"] [av-name="test"]'); 
var homepage_test = "[av-group='homepage'] [av-name='test']" 
var $homepage_test2 = $('[av-group="homepage"] [av-name="test2"]'); 
var homepage_test2 = "[av-group='homepage'] [av-name='test2']" 
var $homepage_test3 = $('[av-group="homepage"] [av-name="test3"]'); 
var homepage_test3 = "[av-group='homepage'] [av-name='test3']" 
var $homepage_mainCon = $('[av-group="homepage"] [av-name="mainCon"]'); 
var homepage_mainCon = "[av-group='homepage'] [av-name='mainCon']" 
var $homepage_registerCon = $('[av-group="homepage"] [av-name="registerCon"]'); 
var homepage_registerCon = "[av-group='homepage'] [av-name='registerCon']" 
var $homepage_termCon = $('[av-group="homepage"] [av-name="termCon"]'); 
var homepage_termCon = "[av-group='homepage'] [av-name='termCon']" 
var $homepage_infoCon = $('[av-group="homepage"] [av-name="infoCon"]'); 
var homepage_infoCon = "[av-group='homepage'] [av-name='infoCon']" 
var $homepage_functionCon = $('[av-group="homepage"] [av-name="functionCon"]'); 
var homepage_functionCon = "[av-group='homepage'] [av-name='functionCon']" 
var $davai_test3 = $('[av-group="davai"] [av-name="test3"]'); 
var davai_test3 = "[av-group='davai'] [av-name='test3']" 
